#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

bsp_io_port_pin_t led[4] = {My_LED1, My_LED2, My_LED3, My_LED4};

int sw12 = 0;
int flag = 0;
int cnt = 1;


/* Callback function */

void irq_callback(external_irq_callback_args_t *p_args)
{
    /* TODO: add your own code here */
    if(p_args -> channel == 1){
        if(sw12==0) sw12 = 1;
    }
    if(p_args -> channel == 4){
        if(flag==0) flag=1;
        else if(flag==1) flag=0;

    }
}

void processPause(){
    while(flag==1){
        R_ICU_ExternalIrqEnable(&g_external_irq2_ctrl);
        if(flag == 0) break;
    }
}

void Recursion(int index, int maxdepth, int depth){
    if(sw12==1) return;
    if(flag==1){
        processPause();
    }
    if(depth==maxdepth){
        R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
        cnt++;
        return;
    }
    R_ICU_ExternalIrqEnable(&g_external_irq1_ctrl);
    R_ICU_ExternalIrqEnable(&g_external_irq2_ctrl);
    if(flag==1){
        processPause();
    }
    for(int i=index;i<4;i++){
        R_IOPORT_PinWrite(&g_ioport_ctrl, led[i], 1);
        //R_BSP_SoftwareDelay (100, BSP_DELAY_UNITS_MILLISECONDS);
        Recursion(i+1, maxdepth, depth+1);
        if(cnt==16) return;
        if(sw12==1) return;
        R_IOPORT_PinWrite(&g_ioport_ctrl, led[i], 0);
        //R_BSP_SoftwareDelay (1000, BSP_DELAY_UNITS_MILLISECONDS);
    }
}




/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */




    while(1){
        R_ICU_ExternalIrqEnable(&g_external_irq1_ctrl);
        R_ICU_ExternalIrqEnable(&g_external_irq2_ctrl);

        if(sw12==1){
            sw12=0;
            for(int i=0;i<4;i++){
                R_IOPORT_PinWrite(&g_ioport_ctrl, led[i], 0);
            }
            cnt=0;
            for(int i=0;i<=4;i++){
                Recursion(0,i,0);
            }

        }

    }


}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {

    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
        R_ICU_ExternalIrqOpen(&g_external_irq1_ctrl, &g_external_irq1_cfg);
        R_ICU_ExternalIrqOpen(&g_external_irq2_ctrl, &g_external_irq2_cfg);



    }

}


